import type { GenerationConfig } from '@/types/project';

export interface PremiumTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  industry: string;
  style: string;
  previewGradient: string;
  accentColor: string;
  tags: string[];
  config: Omit<GenerationConfig, 'aiPrompt'> & { aiPrompt: string };
}

export const PREMIUM_TEMPLATES: PremiumTemplate[] = [
  {
    id: 'obsidian-saas',
    name: 'Obsidian SaaS',
    description: 'Dark cinematic SaaS page with glowing UI, particle effects, and glass-morphism cards.',
    category: 'SaaS / Tech',
    industry: 'Technology',
    style: 'dark',
    previewGradient: 'from-gray-950 via-violet-950 to-gray-950',
    accentColor: '#8b5cf6',
    tags: ['Dark', 'SaaS', 'Animations', 'Glassmorphism', 'AI'],
    config: {
      siteType: 'saas',
      business: {
        name: 'Your SaaS Product',
        tagline: 'The Future of Work, Automated',
        description: 'An AI-powered platform that transforms how teams collaborate and ship products faster.',
        industry: 'SaaS / Technology',
        targetAudience: 'Product teams, developers, and startup founders',
      },
      branding: {
        primaryColor: '#7c3aed',
        secondaryColor: '#0ea5e9',
        accentColor: '#a78bfa',
        surfaceColor: '#09090b',
        fontHeading: 'Space Grotesk',
        fontBody: 'Inter',
        style: 'dark',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'stats', type: 'stats', order: 1 },
        { id: 'features', type: 'features', order: 2 },
        { id: 'pricing', type: 'pricing', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'faq', type: 'faq', order: 5 },
        { id: 'cta', type: 'cta', order: 6 },
      ],
      navigation: {
        navbarStyle: 'dark',
        navbarPosition: 'fixed',
        footerStyle: 'multi-column',
      },
      saas: {
        features: ['AI Automation', 'Team Collaboration', 'Analytics Dashboard', 'API Access', 'Integrations', 'Security'],
        pricingTiers: [
          { name: 'Starter', price: 29, features: ['5 projects', '10GB storage', 'Basic analytics', 'Email support'] },
          { name: 'Pro', price: 79, features: ['Unlimited projects', '100GB storage', 'Advanced analytics', 'Priority support', 'API access'] },
          { name: 'Enterprise', price: 299, features: ['Everything in Pro', 'Custom integrations', 'SSO', 'Dedicated support', 'SLA guarantee'] },
        ],
        hasAuth: true,
        hasDashboard: true,
      },
      aiPrompt: 'Create a STUNNING dark-mode SaaS website. HERO: Full-screen dark (bg-zinc-950) with animated gradient mesh in violet/cyan. Large bold headline with gradient text. Floating UI preview card with glassmorphism (bg-white/5 backdrop-blur border border-white/10). Decorative glow orbs in violet/indigo at corners. FEATURES: Dark glass-morphism cards with gradient icon backgrounds and hover glow border. STATS: Large gradient numbers with count-up animation. PRICING: Dark cards with Most Popular tier highlighted with gradient border glow. OVERALL: Scroll-triggered fade-in animations on every section. Decorative dot/grid patterns as background texture. Ultra-premium dark aesthetic throughout.',
    },
  },
  {
    id: 'ivory-realty',
    name: 'Ivory Realty',
    description: 'Ultra-premium real estate with champagne gold accents, elegant serif typography, and cinematic photography layouts.',
    category: 'Real Estate',
    industry: 'Real Estate / Luxury',
    style: 'elegant',
    previewGradient: 'from-stone-900 via-amber-950 to-stone-900',
    accentColor: '#d4af37',
    tags: ['Luxury', 'Elegant', 'Real Estate', 'Gold', 'Serif'],
    config: {
      siteType: 'business',
      business: {
        name: 'Your Realty Group',
        tagline: 'Where Luxury Meets Home',
        description: 'A premier real estate firm specializing in luxury residential and commercial properties with white-glove service.',
        industry: 'Real Estate',
        targetAudience: 'High-net-worth home buyers and investors',
      },
      branding: {
        primaryColor: '#1c1917',
        secondaryColor: '#d4af37',
        accentColor: '#f5e642',
        surfaceColor: '#fafaf9',
        fontHeading: 'Playfair Display',
        fontBody: 'Inter',
        style: 'elegant',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'features', type: 'features', order: 1 },
        { id: 'gallery', type: 'gallery', order: 2 },
        { id: 'stats', type: 'stats', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'team', type: 'team', order: 5 },
        { id: 'contact', type: 'contact', order: 6 },
      ],
      navigation: {
        navbarStyle: 'transparent',
        navbarPosition: 'fixed',
        footerStyle: 'multi-column',
      },
      aiPrompt: 'Create an ULTRA-LUXURY real estate website. HERO: Full-bleed cinematic image with dark overlay. Playfair Display serif headline in white with thin gold decorative line below. Single gold CTA button. Gold accent lines (border-l-2 border-amber-400) as decorative elements. GALLERY: Asymmetric masonry grid for property images. STATS: Dark bg-stone-900 with gold number text and elegant serif labels. OVERALL: Restrained luxury. Massive whitespace. Thin gold divider lines between sections. Stone-900 / stone-50 / gold (#d4af37) palette only. Slow, dignified fade animations (duration-1000).',
    },
  },
  {
    id: 'titan-fitness',
    name: 'Titan Fitness',
    description: 'High-energy gym brand with dramatic dark backgrounds and electric orange accents that scream power.',
    category: 'Fitness & Health',
    industry: 'Fitness / Gym',
    style: 'bold',
    previewGradient: 'from-gray-950 via-orange-950 to-gray-950',
    accentColor: '#f97316',
    tags: ['Fitness', 'Bold', 'Dark', 'Energy', 'Gym'],
    config: {
      siteType: 'local-service',
      business: {
        name: 'Your Fitness Studio',
        tagline: 'Forged in Iron. Built to Last.',
        description: 'A premium fitness studio offering personal training, group classes, and nutrition coaching.',
        industry: 'Fitness',
        targetAudience: 'Fitness enthusiasts, athletes, and people seeking transformation',
      },
      branding: {
        primaryColor: '#18181b',
        secondaryColor: '#f97316',
        accentColor: '#fb923c',
        surfaceColor: '#09090b',
        fontHeading: 'Outfit',
        fontBody: 'Inter',
        style: 'bold',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'features', type: 'features', order: 1 },
        { id: 'stats', type: 'stats', order: 2 },
        { id: 'pricing', type: 'pricing', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'cta', type: 'cta', order: 5 },
        { id: 'contact', type: 'contact', order: 6 },
      ],
      navigation: {
        navbarStyle: 'dark',
        navbarPosition: 'fixed',
        footerStyle: 'multi-column',
      },
      aiPrompt: 'Create a HIGH-ENERGY fitness/gym website. HERO: Near-black (bg-zinc-950) with dramatic fitness image and dark overlay. Massive bold uppercase headline with orange gradient text. Diagonal orange accent slash decoration. Orange glow CTA button. STATS: Massive orange numbers, dark background, uppercase labels with count-up animation. PRICING: Featured plan with orange gradient header and neon-glow border. CTA: Full-bleed orange gradient section. OVERALL: Maximum contrast. bg-zinc-950 everywhere. Orange (#f97316) is the ONLY accent. Fast punchy animations (duration-300).',
    },
  },
  {
    id: 'maison-restaurant',
    name: 'Maison Fine Dining',
    description: 'Sophisticated restaurant with deep burgundy palette, Playfair Display typography, and warm intimate atmosphere.',
    category: 'Restaurant & Food',
    industry: 'Restaurant',
    style: 'elegant',
    previewGradient: 'from-red-950 via-rose-950 to-amber-950',
    accentColor: '#be123c',
    tags: ['Restaurant', 'Fine Dining', 'Elegant', 'Warm', 'Food'],
    config: {
      siteType: 'local-service',
      business: {
        name: 'Your Restaurant',
        tagline: 'An Experience for the Senses',
        description: 'A fine dining restaurant celebrating seasonal ingredients and artisan techniques in an intimate setting.',
        industry: 'Restaurant',
        targetAudience: 'Food lovers, couples, business diners, special occasions',
      },
      branding: {
        primaryColor: '#881337',
        secondaryColor: '#92400e',
        accentColor: '#fbbf24',
        surfaceColor: '#1c1008',
        fontHeading: 'Playfair Display',
        fontBody: 'Lora',
        style: 'elegant',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'about', type: 'about', order: 1 },
        { id: 'features', type: 'features', order: 2 },
        { id: 'gallery', type: 'gallery', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'cta', type: 'cta', order: 5 },
        { id: 'contact', type: 'contact', order: 6 },
      ],
      navigation: {
        navbarStyle: 'transparent',
        navbarPosition: 'fixed',
        footerStyle: 'multi-column',
      },
      aiPrompt: 'Create an EXQUISITE fine dining restaurant website. HERO: Full-screen image with deep warm overlay (bg-gradient-to-b from-transparent to-stone-950/90). Playfair Display serif headline in cream with thin gold separator line. Elegant reservation CTA. ABOUT: Split layout, evocative text + food image. Lora serif body text. GALLERY: Full-bleed masonry food photography. OVERALL: Warm palette — deep burgundy (#881337), stone/cream, gold accents. Slow luxurious fade-ins (duration-1000). Feels like a Michelin-starred restaurant.',
    },
  },
  {
    id: 'nova-agency',
    name: 'Nova Creative Agency',
    description: 'Visually explosive agency site with bold typography, multi-color gradients, and editorial layouts.',
    category: 'Creative & Agency',
    industry: 'Creative Agency',
    style: 'vibrant',
    previewGradient: 'from-fuchsia-600 via-violet-600 to-pink-600',
    accentColor: '#d946ef',
    tags: ['Agency', 'Creative', 'Bold', 'Colorful', 'Animations'],
    config: {
      siteType: 'business',
      business: {
        name: 'Your Creative Agency',
        tagline: 'We Make the Impossible Visible',
        description: 'A full-service creative agency delivering brand strategy, digital design, and development.',
        industry: 'Creative Agency',
        targetAudience: 'Startups, brands, and companies needing design and digital marketing',
      },
      branding: {
        primaryColor: '#9333ea',
        secondaryColor: '#ec4899',
        accentColor: '#f0abfc',
        surfaceColor: '#fdf4ff',
        fontHeading: 'Sora',
        fontBody: 'DM Sans',
        style: 'vibrant',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'features', type: 'features', order: 1 },
        { id: 'gallery', type: 'gallery', order: 2 },
        { id: 'stats', type: 'stats', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'team', type: 'team', order: 5 },
        { id: 'cta', type: 'cta', order: 6 },
      ],
      navigation: {
        navbarStyle: 'solid',
        navbarPosition: 'fixed',
        footerStyle: 'multi-column',
      },
      aiPrompt: 'Create a VISUALLY EXPLOSIVE creative agency website. HERO: White background with enormous gradient headline (purple to pink gradient text) spanning two lines. Asymmetric layout with bold abstract color block shapes as decoration. Gradient CTA button with hover glow. SERVICES: Oversized number labels (01, 02, 03) in faint gradient text. Each service card gets hover gradient background reveal. GALLERY: Irregular mosaic portfolio grid with mixed cell sizes. STATS: Bold gradient numbers. CTA: Full gradient background section (purple to pink) with white text. OVERALL: Bold typographic hierarchy. Lots of whitespace. Magenta/violet/pink palette. Energetic but sophisticated.',
    },
  },
  {
    id: 'meridian-health',
    name: 'Meridian Health',
    description: 'Clean, trustworthy healthcare website with calming blues and conversion-focused layout for patient acquisition.',
    category: 'Healthcare',
    industry: 'Healthcare / Medical',
    style: 'minimal',
    previewGradient: 'from-sky-600 via-blue-600 to-teal-600',
    accentColor: '#0284c7',
    tags: ['Healthcare', 'Medical', 'Clean', 'Professional', 'Trust'],
    config: {
      siteType: 'local-service',
      business: {
        name: 'Your Medical Practice',
        tagline: 'Compassionate Care, Expert Results',
        description: 'A modern medical practice offering comprehensive primary care and preventive health services.',
        industry: 'Healthcare',
        targetAudience: 'Patients of all ages seeking quality medical care',
      },
      branding: {
        primaryColor: '#0369a1',
        secondaryColor: '#0d9488',
        accentColor: '#38bdf8',
        surfaceColor: '#f0f9ff',
        fontHeading: 'Plus Jakarta Sans',
        fontBody: 'Inter',
        style: 'minimal',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'features', type: 'features', order: 1 },
        { id: 'stats', type: 'stats', order: 2 },
        { id: 'about', type: 'about', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'team', type: 'team', order: 5 },
        { id: 'faq', type: 'faq', order: 6 },
        { id: 'contact', type: 'contact', order: 7 },
      ],
      navigation: {
        navbarStyle: 'solid',
        navbarPosition: 'sticky',
        footerStyle: 'multi-column',
      },
      aiPrompt: 'Create a PROFESSIONAL, TRUSTWORTHY healthcare website. HERO: Clean white with sky-blue gradient accent. Split layout with headline and book-appointment CTA, plus trust badges (certifications). Sky-blue CTA button. FEATURES: Clean white cards with sky-blue icon backgrounds. STATS: Sky-blue accent section with trust numbers. TEAM: Professional headshots in circular frames with clear credentials. FAQ: Smooth accordion. OVERALL: Clean, airy whitespace. Sky blue (#0369a1) and teal palette. Maximum trust signals. Gentle fade-in animations (duration-700).',
    },
  },
  {
    id: 'luxe-ecommerce',
    name: 'Luxe Store',
    description: 'Premium e-commerce with editorial photography, minimal typography, and sophisticated shopping experience.',
    category: 'E-Commerce',
    industry: 'Fashion / Retail',
    style: 'minimal',
    previewGradient: 'from-neutral-900 via-stone-800 to-neutral-900',
    accentColor: '#e7e5e4',
    tags: ['E-Commerce', 'Fashion', 'Minimal', 'Editorial', 'Premium'],
    config: {
      siteType: 'ecommerce',
      business: {
        name: 'Your Brand Store',
        tagline: 'Curated for the Discerning',
        description: 'A premium fashion and lifestyle brand with carefully curated collections.',
        industry: 'Fashion / Retail',
        targetAudience: 'Style-conscious consumers aged 25-45',
      },
      branding: {
        primaryColor: '#1c1917',
        secondaryColor: '#44403c',
        accentColor: '#d6d3d1',
        surfaceColor: '#fafaf9',
        fontHeading: 'Manrope',
        fontBody: 'Inter',
        style: 'minimal',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'product-grid', type: 'product-grid', order: 1 },
        { id: 'features', type: 'features', order: 2 },
        { id: 'gallery', type: 'gallery', order: 3 },
        { id: 'testimonials', type: 'testimonials', order: 4 },
        { id: 'cta', type: 'cta', order: 5 },
      ],
      navigation: {
        navbarStyle: 'solid',
        navbarPosition: 'sticky',
        footerStyle: 'multi-column',
      },
      ecommerce: {
        products: [
          { name: 'Essential Tee', price: 85, category: 'Clothing' },
          { name: 'Linen Trousers', price: 195, category: 'Clothing' },
          { name: 'Leather Bag', price: 340, category: 'Accessories' },
          { name: 'Cashmere Sweater', price: 280, category: 'Clothing' },
          { name: 'Canvas Sneakers', price: 150, category: 'Footwear' },
          { name: 'Silk Scarf', price: 120, category: 'Accessories' },
        ],
        cartEnabled: true,
        checkoutEnabled: false,
        currency: 'USD',
      },
      aiPrompt: 'Create an ULTRA-MINIMAL editorial e-commerce website inspired by Celine and Muji. HERO: Oversized full-bleed photography, minimal text overlay, thin-weight headline, simple text-link CTA with arrow. PRODUCT GRID: Clean 3-4 column grid with generous whitespace. Hover reveals name and price only. No card backgrounds. GALLERY: Full editorial spread with asymmetric mixed-size image layout. OVERALL: 90% white space. Stone-50 background. Stone-900 text. Almost no color. Thin horizontal rules (border-t border-stone-200) between sections. Typography does all the work.',
    },
  },
  {
    id: 'axiom-law',
    name: 'Axiom Professional',
    description: 'Commanding navy-toned professional services for law firms and financial advisors. Radiates authority and trust.',
    category: 'Professional Services',
    industry: 'Legal / Finance',
    style: 'corporate',
    previewGradient: 'from-slate-900 via-blue-950 to-slate-900',
    accentColor: '#1d4ed8',
    tags: ['Law', 'Finance', 'Corporate', 'Professional', 'Navy'],
    config: {
      siteType: 'business',
      business: {
        name: 'Your Law Firm',
        tagline: 'Protecting What Matters Most',
        description: 'A full-service legal firm providing expert counsel in corporate law, litigation, and estate planning.',
        industry: 'Legal Services',
        targetAudience: 'Individuals and businesses needing legal representation',
      },
      branding: {
        primaryColor: '#1e3a5f',
        secondaryColor: '#1d4ed8',
        accentColor: '#60a5fa',
        surfaceColor: '#f8fafc',
        fontHeading: 'Playfair Display',
        fontBody: 'Inter',
        style: 'corporate',
      },
      sections: [
        { id: 'hero', type: 'hero', order: 0 },
        { id: 'features', type: 'features', order: 1 },
        { id: 'about', type: 'about', order: 2 },
        { id: 'stats', type: 'stats', order: 3 },
        { id: 'team', type: 'team', order: 4 },
        { id: 'testimonials', type: 'testimonials', order: 5 },
        { id: 'faq', type: 'faq', order: 6 },
        { id: 'contact', type: 'contact', order: 7 },
      ],
      navigation: {
        navbarStyle: 'solid',
        navbarPosition: 'sticky',
        footerStyle: 'multi-column',
      },
      aiPrompt: 'Create an AUTHORITATIVE professional services website. HERO: Deep navy background (bg-slate-900) with professional image and dark overlay. Playfair Display serif headline in white. Two CTAs: navy filled and ghost white border. Trust badges: bar association logos, years established. FEATURES: Clean white cards on slate-50. Navy icon squares, Playfair Display headings. STATS: Dark navy section with large white numbers and blue accent text. "250+ Cases Won", "30+ Years", "98% Success Rate". TEAM: Professional headshots in square frames with clear titles and credentials. OVERALL: Navy (#1e3a5f) and white palette. Blue for accents only. Professional dignified fade-in animations.',
    },
  },
];

export function getTemplateById(id: string): PremiumTemplate | undefined {
  return PREMIUM_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): PremiumTemplate[] {
  if (category === 'All') return PREMIUM_TEMPLATES;
  return PREMIUM_TEMPLATES.filter((t) => t.category === category);
}

export const TEMPLATE_CATEGORIES = [
  'All',
  'SaaS / Tech',
  'Real Estate',
  'Fitness & Health',
  'Restaurant & Food',
  'Creative & Agency',
  'Healthcare',
  'E-Commerce',
  'Professional Services',
];

