/**
 * The questions worth asking once a site exists.
 *
 * The intake deliberately builds first and asks nothing, which is right for
 * the wow-moment but leaves the model inventing the things it could not know:
 * a wordmark when the owner already has a logo, a phone number, opening hours,
 * neighbourhoods it serves. And nobody ever asked where leads should be sent,
 * so alerts went to whatever address the account was signed up with.
 *
 * Two kinds of question:
 *
 *  - PRACTICAL: logo, lead email, phone, hours, service area. Same for every
 *    business, each one changing something concrete on the site or in the
 *    plumbing behind it.
 *  - PROBING: what the owner actually does and what they need the site to do.
 *    These are per-trade, because "what's your busiest service?" is a useful
 *    question for a roofer and a meaningless one for a law firm.
 *
 * The probing set is derived from the trade rather than generated by a model.
 * That keeps this working with no API key, no spend and no latency, and the
 * questions stay good because they were written for the trade rather than
 * improvised per request.
 */

export type FollowUpKind = 'text' | 'longtext' | 'email' | 'tel' | 'logo' | 'hours';

export interface FollowUpQuestion {
  id: string;
  label: string;
  /** Shown under the label — why we're asking, in the owner's terms. */
  help?: string;
  kind: FollowUpKind;
  placeholder?: string;
  required?: boolean;
}

const PRACTICAL: FollowUpQuestion[] = [
  {
    id: 'logo',
    label: 'Do you have a logo?',
    help: 'Upload it and we will use it across the site. Skip this and we will keep the one we designed.',
    kind: 'logo',
  },
  {
    id: 'lead_email',
    label: 'Where should enquiries and bookings be sent?',
    help: 'Every form and booking on your site emails this address. Use the inbox you actually watch.',
    kind: 'email',
    placeholder: 'you@yourbusiness.com',
    required: true,
  },
  {
    id: 'phone',
    label: "What's your business phone number?",
    help: 'It goes in the header, the footer and on booking confirmations.',
    kind: 'tel',
    placeholder: '(555) 123-4567',
  },
  {
    id: 'hours',
    label: 'When are you open?',
    help: 'Shown on the site and used to stop people booking outside your hours.',
    kind: 'hours',
  },
  {
    id: 'service_area',
    label: 'Which areas do you serve?',
    help: 'Towns, a radius, or the whole city. This is what local searches match on.',
    kind: 'text',
    placeholder: 'Rhinebeck, Kingston, Beacon — within 30 miles',
  },
];

interface ProbeSet {
  match: RegExp;
  questions: FollowUpQuestion[];
}

/** Trade-specific questions, most specific match wins. */
const PROBES: ProbeSet[] = [
  {
    match: /restaurant|cafe|café|bistro|takeaway|pizzeria|bakery|deli|catering|food/i,
    questions: [
      { id: 'probe_signature', label: 'What do people come back for?', help: 'The dish or two you are known for — these lead the page.', kind: 'longtext' },
      { id: 'probe_occasion', label: 'Who is a typical table?', help: 'Date night, families, business lunch? It changes the tone and the photography.', kind: 'longtext' },
      { id: 'probe_action', label: 'What should a hungry visitor do first?', help: 'Book a table, order online, or look at the menu?', kind: 'text' },
    ],
  },
  {
    match: /roof|plumb|hvac|electric|landscap|lawn|contractor|construction|remodel|renovat|paving|fencing|clean|pest|window|gutter|flooring|painting|handyman/i,
    questions: [
      { id: 'probe_bread_butter', label: 'Which job do you most want more of?', help: 'The work that pays best or fills the schedule — we lead with that instead of listing everything equally.', kind: 'longtext' },
      { id: 'probe_proof', label: 'Why do customers pick you over the next quote?', help: 'Licences, guarantees, years, a crew that turns up — the thing you would say on a doorstep.', kind: 'longtext' },
      { id: 'probe_urgency', label: 'Do you do emergency or same-day work?', help: 'If so the site should shout it; if not we keep the tone calm and considered.', kind: 'text' },
    ],
  },
  {
    match: /salon|spa|barber|beauty|aesthetic|massage|nail|lash|tattoo|grooming/i,
    questions: [
      { id: 'probe_treatments', label: 'Which treatments do you want booked most?', help: 'These get the space; the rest go in a list.', kind: 'longtext' },
      { id: 'probe_client', label: 'Describe your ideal client.', help: 'It sets the whole look — a bridal salon and a walk-in barber should not look alike.', kind: 'longtext' },
      { id: 'probe_walkins', label: 'Appointments only, or walk-ins too?', kind: 'text' },
    ],
  },
  {
    match: /clinic|dental|dentist|medical|doctor|health|therapy|therapist|chiropract|veterinar|wellness/i,
    questions: [
      { id: 'probe_patients', label: 'Are you taking new patients, and for what?', help: 'Decides whether the site pushes booking or reassurance.', kind: 'longtext' },
      { id: 'probe_concerns', label: 'What worries people before they call you?', help: 'Cost, pain, waiting times — we answer it on the page instead of leaving them guessing.', kind: 'longtext' },
      { id: 'probe_insurance', label: 'Which insurance or payment options do you accept?', kind: 'text' },
    ],
  },
  {
    match: /gym|fitness|yoga|pilates|crossfit|personal train|martial arts|dance|coach/i,
    questions: [
      { id: 'probe_member', label: 'Who is your typical member?', help: 'Complete beginners and competitive athletes need very different sites.', kind: 'longtext' },
      { id: 'probe_offer', label: "What's the first step you want someone to take?", help: 'A free week, a trial class, a consultation?', kind: 'text' },
      { id: 'probe_difference', label: 'What do you do that the big chain down the road does not?', kind: 'longtext' },
    ],
  },
  {
    match: /law|legal|attorney|solicitor|accountan|bookkeep|financial advis|insurance|consultan|advisory|architect|surveyor/i,
    questions: [
      { id: 'probe_matters', label: 'Which matters do you want to be approached about?', help: 'We lead with these and leave out work you would rather not take.', kind: 'longtext' },
      { id: 'probe_client', label: 'Who is the client — individuals, or businesses?', kind: 'text' },
      { id: 'probe_first_step', label: 'What happens when someone first contacts you?', help: 'A free consultation? A callback? Saying so removes the hesitation.', kind: 'longtext' },
    ],
  },
  {
    match: /shop|store|retail|e-?commerce|boutique|apparel|clothing|jewel|product/i,
    questions: [
      { id: 'probe_hero_product', label: 'Which products should lead?', help: 'Your best sellers get the front page rather than a flat grid of everything.', kind: 'longtext' },
      { id: 'probe_buyer', label: 'Who buys from you?', kind: 'longtext' },
      { id: 'probe_shipping', label: 'Where do you ship, and how fast?', help: 'One of the most common reasons a cart gets abandoned.', kind: 'text' },
    ],
  },
  {
    match: /real estate|realty|realtor|estate agent|property|lettings|brokerage/i,
    questions: [
      { id: 'probe_market', label: 'Which market do you specialise in?', help: 'First-time buyers, luxury, rentals, commercial — it changes everything.', kind: 'longtext' },
      { id: 'probe_side', label: 'Do you mostly represent buyers or sellers?', kind: 'text' },
      { id: 'probe_edge', label: 'What do you do that other agents in the area do not?', kind: 'longtext' },
    ],
  },
];

const DEFAULT_PROBES: FollowUpQuestion[] = [
  { id: 'probe_what_you_do', label: 'In your own words, what does the business do?', help: 'Plain language, the way you would tell a neighbour. It tends to beat anything we would write for you.', kind: 'longtext' },
  { id: 'probe_customer', label: 'Who is your best customer?', kind: 'longtext' },
  { id: 'probe_action', label: 'What is the one thing you want visitors to do?', help: 'Call, book, buy, or send an enquiry?', kind: 'text' },
];

export interface FollowUpSet {
  probing: FollowUpQuestion[];
  practical: FollowUpQuestion[];
}

export function buildFollowUpQuestions(input: {
  industry?: string;
  description?: string;
  siteType?: string;
}): FollowUpSet {
  const haystack = [input.industry, input.description, input.siteType].filter(Boolean).join(' ');
  const probe = PROBES.find((entry) => entry.match.test(haystack));
  return {
    probing: probe ? probe.questions : DEFAULT_PROBES,
    practical: PRACTICAL,
  };
}

/** Ids whose answers change what visitors see and so warrant a site edit. */
export const VISIBLE_ON_SITE = new Set([
  'logo',
  'phone',
  'hours',
  'service_area',
  'probe_signature',
  'probe_bread_butter',
  'probe_treatments',
  'probe_matters',
  'probe_hero_product',
  'probe_market',
  'probe_offer',
  'probe_action',
]);
